// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqsiusbbjwzboytkgreb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhxc2l1c2Jiand6Ym95dGtncmViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk1NjUyNzcsImV4cCI6MjA3NTE0MTI3N30.uPBGjXVS7SOun1XhK7GW6EBP-DHtC0QdVwGUjdCA5eI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});